# ==============================================================
# Configuracion de la aplicacion
# ==============================================================
spring.application.name=BarberTime
server.port=8080

# ==============================================================
# Thymeleaf
# ==============================================================
spring.thymeleaf.cache=false

# ==============================================================
# Conexion MySQL
# ==============================================================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==============================================================
# JPA / Hibernate
# ==============================================================
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

# ==============================================================
# Logs
# ==============================================================
logging.level.root=INFO
logging.level.com.barbertime=DEBUG