# ==============================================================
# Configuracion de la aplicacion
# ==============================================================
spring.application.name=BarberTime
server.port=8080

# Recargar plantillas Thymeleaf sin reiniciar
spring.thymeleaf.cache=false

# ==============================================================
# Conexion a MySQL
# ==============================================================
# Cambiamos tiendadb por barbertime_db
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/barbertime_db?createDatabaseIfNotExist=true}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:admin} 
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==============================================================
# JPA / Hibernate
# ==============================================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=true

# ==============================================================
# Logs
# ==============================================================
logging.level.root=INFO
logging.level.com.barbertime=DEBUG 